name: Jave Application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-java:

    run-on: ubuntu-latest

    steps:
      -uses: action/checkout@v2

      -name: setup the JDK
       uses: action/setup-java@v1
       with:
         java-version: 1.8

        -name: Grunt Permission
         run: chmod +x gradlew
